name: macOS

on:
  push:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs: 
  build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository with LFS support
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Enable cache
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.1.6f1c1
          targetPlatform: StandaloneOSX
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build-macOS
          path: build